name: "Check Nexus credentials"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'alandtse/MergeMapper'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x.x
      - name: Download BUTR.NexusUploader
        run: dotnet tool install -g BUTR.NexusUploader
      - name: Check Nexus session cookie
        # https://github.com/BUTR/BUTR.NexusUploader
        env:
          UNEX_SESSION_COOKIE: ${{ secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
        run: |
          unex check --session-cookie "$UNEX_SESSION_COOKIE"
      - name: Check Nexus API Key
        # https://github.com/BUTR/BUTR.NexusUploader
        # https://www.nexusmods.com/users/myaccount?tab=api%20access
        env:
          UNEX_APIKEY: ${{ secrets.UNEX_APIKEY }}
        run: |
          unex check --key "$UNEX_APIKEY"
